// src/routes/resume/+page.svelte
<script>
  import Education from '$lib/components/Education.svelte'

  import Items from '$lib/components/Items.svelte'
  import Section from '$lib/components/Section.svelte'

  import portfolio from '$lib/portfolio.yaml'
</script>

<div id="resume">
  <div id="header">
    <h2>Nicholas Baker</h2>
    <div>
      <p>
        <img
          alt="location"
          src="https://img.icons8.com/material-rounded/192/ffffff/address.png"
          width="20px"
        />
        &nbsp; Plano, TX
      </p>
      <p>
        <img
          alt="phone"
          src="https://img.icons8.com/fluency-systems-filled/96/ffffff/phone.png"
          width="20px"
        />
        &nbsp; (972) 330-6048
      </p>
      <p>
        <img
          alt="email"
          src="https://img.icons8.com/material-rounded/192/ffffff/mail.png"
          width="20px"
        />
        &nbsp;
        <a href="mailto:ndbaker1@outlook.com" target="_blank">ndbaker1@outlook.com</a>
      </p>
      <p>
        <img
          alt="github"
          src="https://img.icons8.com/ios-glyphs/120/ffffff/repository.png"
          width="20px"
        />
        &nbsp;
        <a href="https://github.com/ndbaker1" target="_blank">github.com/ndbaker1</a>
      </p>
    </div>
  </div>

  <div id="side">
    <Section title="education">
      {#each portfolio.education as edu}
        <Education props={edu} />
      {/each}
    </Section>

    <Section title="skills">
      <h4>Tools</h4>
      <p>{portfolio.skills.tools.join(', ')}</p>
      <h4>Languages</h4>
      <p>{portfolio.skills.languages.join(', ')}</p>
    </Section>
  </div>

  <div id="main">
    <Section title="work experience">
      {#each portfolio.work as work}
        <Items
          type="work"
          position={work.position}
          company={work.company}
          location={work.location}
          date={work.date}
          items={work.items}
        />
      {/each}
    </Section>

    <Section title="competitions">
      {#each portfolio.competitions as comp}
        <Items
          type="competition"
          event={comp.event}
          dateAndPlace={comp.date + ' | ' + comp.location}
          items={comp.items}
        />
      {/each}
    </Section>
  </div>
</div>

<style>
  #resume {
    /* dimensions of letter paper */
    width: 8.5in;
    height: 11in;
    /* remove top/bottom margins and center */
    margin: 0 auto;
    /* organize other components in a grid */
    display: grid;
    grid-auto-columns: 18rem auto;
    grid-auto-rows: min-content 1fr;
    grid-template-areas:
      'header main'
      'side main';

    box-shadow: 0 0 1rem rgba(0, 0, 0, 0.5);
  }

  p {
    font-size: 0.85rem;
    margin: 0.2rem 0;
    align-items: center;
  }

  img {
    vertical-align: bottom;
  }

  h2,
  h4 {
    margin-bottom: 0;
  }

  #header {
    grid-area: header;
    background-color: rgb(57, 57, 57);
    color: whitesmoke;
    padding: 1.5rem;
  }

  #side {
    grid-area: side;
    background-color: rgb(250, 250, 250);
    padding: 1.5rem;
  }

  #main {
    grid-area: main;
    background-color: white;
    padding: 1.5rem;
  }
</style>

// src/Resume.tsx
import { Component, For, ParentProps } from 'solid-js'
import './Resume.scss'


export const Info: Component = () => {
  return (
    <>
      <h2>Nicholas Baker</h2>
      <div>
        <p><img src="https://img.icons8.com/material-rounded/192/ffffff/address.png" width="20px" /> Plano, TX</p >
        <p><img src="https://img.icons8.com/fluency-systems-filled/96/ffffff/phone.png" width="20px" /> (972) 330-6048</p >
        <p><img src="https://img.icons8.com/material-rounded/192/ffffff/mail.png" width="20px" />
          <a href="mailto:ndbaker1@outlook.com">ndbaker1@outlook.com</a>
        </p>
        <p><img src="https://img.icons8.com/ios-glyphs/120/ffffff/repository.png" width="20px" />
          <a href="https://github.com/ndbaker1">github.com/ndbaker1</a>
        </p>
      </div>
    </>
  )
}

export const SkillsSection: Component = () => {
  return (
    <div id="skills">
      <h2 class="section-title">skills</h2>
      <hr />
      <div>
        <h4>Tools</h4>
        <p>
          Docker, React, Angular, Spring, Hibernate, Jenkins, PostgreSQL, Terraform, Maven, Google Cloud Platform,
          Android, OAuth, Svelte
        </p>
        <h4>Languages</h4>
        <p>
          Rust, Kotlin, Typescript & Javascript, Python, HTML/CSS, Java, C/C++, SQL, GraphQL, Shell Scripting
        </p>
      </div>
    </div>
  )
}

type EducationProps = {
  title: string
  location: string
  date: string
}

export const Education: Component<EducationProps> = (props) => {
  return (
    <div>
      <h4> {props.title} </h4>
      <p> {props.location} </p>
      <p>
        <img src="https://img.icons8.com/material-outlined/192/calendar--v1.png" width="20px" />
        {props.date}
      </p>
    </div>
  )
}

type WorkProps = {
  position: string
  location: string
  company: string
  date: string
  items: string[]
}

export const Work: Component<WorkProps> = (props) => {
  return (
    <div class="summary">
      <h4>{props.position}</h4>
      <p>{props.company} <br /> {props.date} | {props.location} </p>

      <ul>
        <For each={props.items}>
          {note => <li> <p> {note} </p> </li>}
        </For>
      </ul>
    </div>
  )
}

type SectionProps = ParentProps & {
  title: string
}

export const Section: Component<SectionProps> = (props) => {
  return (
    <div>
      <h2 class="section-title">{props.title}</h2>
      <hr />
      {props.children}
    </div>
  )
}

type CompetitionProps = {
  event: string
  dateAndPlace: string
  items: string[]
}

export const Competition: Component<CompetitionProps> = (props) => {
  return (
    <div class="summary">
      <h4> {props.event} </h4>
      <p> {props.dateAndPlace} </p>
      <ul>
        <For each={props.items}>
          {item => <li> <p> {item} </p> </li>}
        </For>
      </ul>
    </div>
  )
}
